# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://my.issue.tracker/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="psitools" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
# A display name for the mod
displayName="PsiTools" #mandatory
# A file name (in the root of the mod JAR) containing a logo for display
# A text field displayed in the mod UI
# A text field displayed in the mod UI
authors="Macrophage" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''

    Adding some new tricks, operators, and simplifying the 10th grade math a little.

'''

[[dependencies.psitools]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.psitools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.psitools]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.15.2-1.2-27,)"
    side="BOTH"

[[dependencies.psitools]]
    modId="psi"
    mandatory=true
    versionRange="[r1.2-82,)"
    side="BOTH"
